export interface Fixture {
  /** A short, human-readable test name. */
  name: string;
  rule: string;
  locale: 'en' | 'ru';
  expected: string;
}

/**
 * Golden fixtures covering every FREQ value, INTERVAL, COUNT, UNTIL, BYDAY
 * (including numeric-prefixed shorthand and BYSETPOS), BYMONTHDAY (including
 * negative), BYMONTH, and combinations thereof, for both bundled locales.
 *
 * These strings were generated by this library itself and hand-reviewed for
 * grammatical correctness (particularly the Russian case/gender agreement).
 * `tests/regression.test.ts` cross-checks the `en` subset against `rrule`'s
 * own `toText()` and documents every intentional divergence.
 */
export const fixtures: Fixture[] = [
  // ---- Baseline frequencies, no modifiers ----
  { name: 'yearly plain (en)', rule: 'FREQ=YEARLY', locale: 'en', expected: 'Every year' },
  { name: 'yearly plain (ru)', rule: 'FREQ=YEARLY', locale: 'ru', expected: 'Каждый год' },
  { name: 'monthly plain (en)', rule: 'FREQ=MONTHLY', locale: 'en', expected: 'Every month' },
  { name: 'monthly plain (ru)', rule: 'FREQ=MONTHLY', locale: 'ru', expected: 'Каждый месяц' },
  { name: 'weekly plain (en)', rule: 'FREQ=WEEKLY', locale: 'en', expected: 'Every week' },
  { name: 'weekly plain (ru)', rule: 'FREQ=WEEKLY', locale: 'ru', expected: 'Каждую неделю' },

  // ---- DAILY + INTERVAL, incl. Russian numeral edge cases (1, 2, 5, 11, 21, 25) ----
  {
    name: 'daily interval 1 (en)',
    rule: 'FREQ=DAILY;INTERVAL=1',
    locale: 'en',
    expected: 'Every day',
  },
  {
    name: 'daily interval 1 (ru)',
    rule: 'FREQ=DAILY;INTERVAL=1',
    locale: 'ru',
    expected: 'Каждый день',
  },
  {
    name: 'daily interval 2 (en)',
    rule: 'FREQ=DAILY;INTERVAL=2',
    locale: 'en',
    expected: 'Every 2 days',
  },
  {
    name: 'daily interval 2 (ru)',
    rule: 'FREQ=DAILY;INTERVAL=2',
    locale: 'ru',
    expected: 'Каждые 2 дня',
  },
  {
    name: 'daily interval 5 (ru)',
    rule: 'FREQ=DAILY;INTERVAL=5',
    locale: 'ru',
    expected: 'Каждые 5 дней',
  },
  {
    name: 'daily interval 11 (ru)',
    rule: 'FREQ=DAILY;INTERVAL=11',
    locale: 'ru',
    expected: 'Каждые 11 дней',
  },
  {
    name: 'daily interval 21 (ru)',
    rule: 'FREQ=DAILY;INTERVAL=21',
    locale: 'ru',
    expected: 'Каждые 21 день',
  },
  {
    name: 'daily interval 25 (ru)',
    rule: 'FREQ=DAILY;INTERVAL=25',
    locale: 'ru',
    expected: 'Каждые 25 дней',
  },

  // ---- WEEKLY + BYDAY: one day, several days, and the "every weekday" / "weekend" special cases ----
  {
    name: 'weekly one weekday (en)',
    rule: 'FREQ=WEEKLY;BYDAY=MO',
    locale: 'en',
    expected: 'Every week on Monday',
  },
  {
    name: 'weekly one weekday (ru)',
    rule: 'FREQ=WEEKLY;BYDAY=MO',
    locale: 'ru',
    expected: 'Каждую неделю по понедельникам',
  },
  {
    name: 'weekly several weekdays (en)',
    rule: 'FREQ=WEEKLY;BYDAY=MO,WE,FR',
    locale: 'en',
    expected: 'Every week on Monday, Wednesday and Friday',
  },
  {
    name: 'weekly several weekdays (ru)',
    rule: 'FREQ=WEEKLY;BYDAY=MO,WE,FR',
    locale: 'ru',
    expected: 'Каждую неделю по понедельникам, средам и пятницам',
  },
  {
    name: 'daily + full business week collapses to "on weekdays" (en)',
    rule: 'FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR',
    locale: 'en',
    expected: 'On weekdays',
  },
  {
    name: 'daily + full business week collapses to "по будням" (ru)',
    rule: 'FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR',
    locale: 'ru',
    expected: 'По будням',
  },
  {
    name: 'weekly + Sat/Sun collapses to "on weekends" (en)',
    rule: 'FREQ=WEEKLY;BYDAY=SA,SU',
    locale: 'en',
    expected: 'Every week on weekends',
  },
  {
    name: 'weekly + Sat/Sun collapses to "по выходным" (ru)',
    rule: 'FREQ=WEEKLY;BYDAY=SA,SU',
    locale: 'ru',
    expected: 'Каждую неделю по выходным',
  },

  // ---- MONTHLY + BYMONTHDAY: positive, negative, and "last day" ----
  {
    name: 'monthly last day (en)',
    rule: 'FREQ=MONTHLY;BYMONTHDAY=-1',
    locale: 'en',
    expected: 'Every month on the last day of the month',
  },
  {
    name: 'monthly last day (ru)',
    rule: 'FREQ=MONTHLY;BYMONTHDAY=-1',
    locale: 'ru',
    expected: 'Каждый месяц в последний день месяца',
  },
  {
    name: 'monthly two positive month-days (en)',
    rule: 'FREQ=MONTHLY;BYMONTHDAY=1,15',
    locale: 'en',
    expected: 'Every month on the 1st and 15th',
  },
  {
    name: 'monthly two positive month-days (ru)',
    rule: 'FREQ=MONTHLY;BYMONTHDAY=1,15',
    locale: 'ru',
    expected: 'Каждый месяц 1-го и 15-го числа',
  },
  {
    name: 'monthly 2nd-to-last day (en)',
    rule: 'FREQ=MONTHLY;BYMONTHDAY=-2',
    locale: 'en',
    expected: 'Every month on the 2nd-to-last day of the month',
  },
  {
    name: 'monthly 2nd-to-last day (ru)',
    rule: 'FREQ=MONTHLY;BYMONTHDAY=-2',
    locale: 'ru',
    expected: 'Каждый месяц 2-й день с конца месяца',
  },

  // ---- MONTHLY + BYDAY + BYSETPOS ("the Nth weekday") -- every weekday gender, RU ----
  {
    name: 'monthly 1st Monday (en)',
    rule: 'FREQ=MONTHLY;BYDAY=MO;BYSETPOS=1',
    locale: 'en',
    expected: 'Every month on the 1st Monday',
  },
  {
    name: 'monthly 1st Monday, masculine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=MO;BYSETPOS=1',
    locale: 'ru',
    expected: 'Каждый месяц в первый понедельник',
  },
  {
    name: 'monthly 1st Tuesday, masculine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=TU;BYSETPOS=1',
    locale: 'ru',
    expected: 'Каждый месяц в первый вторник',
  },
  {
    name: 'monthly 1st Wednesday, feminine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=WE;BYSETPOS=1',
    locale: 'ru',
    expected: 'Каждый месяц в первую среду',
  },
  {
    name: 'monthly 1st Thursday, masculine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=TH;BYSETPOS=1',
    locale: 'ru',
    expected: 'Каждый месяц в первый четверг',
  },
  {
    name: 'monthly 1st Friday, feminine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=FR;BYSETPOS=1',
    locale: 'ru',
    expected: 'Каждый месяц в первую пятницу',
  },
  {
    name: 'monthly 1st Saturday, feminine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=SA;BYSETPOS=1',
    locale: 'ru',
    expected: 'Каждый месяц в первую субботу',
  },
  {
    name: 'monthly 1st Sunday, neuter (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=SU;BYSETPOS=1',
    locale: 'ru',
    expected: 'Каждый месяц в первое воскресенье',
  },
  {
    name: 'monthly last Friday, shorthand -1FR (en)',
    rule: 'FREQ=MONTHLY;BYDAY=-1FR',
    locale: 'en',
    expected: 'Every month on the last Friday',
  },
  {
    name: 'monthly last Friday, shorthand -1FR, feminine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=-1FR',
    locale: 'ru',
    expected: 'Каждый месяц в последнюю пятницу',
  },
  {
    name: 'monthly mixed shorthand 1MO,-1FR (en)',
    rule: 'FREQ=MONTHLY;BYDAY=1MO,-1FR',
    locale: 'en',
    expected: 'Every month on the 1st Monday and on the last Friday',
  },
  {
    name: 'monthly mixed shorthand 1MO,-1FR (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=1MO,-1FR',
    locale: 'ru',
    expected: 'Каждый месяц в первый понедельник и в последнюю пятницу',
  },

  // ---- YEARLY + BYMONTH ----
  {
    name: 'yearly two months (en)',
    rule: 'FREQ=YEARLY;BYMONTH=1,6',
    locale: 'en',
    expected: 'In January and June',
  },
  {
    name: 'yearly two months (ru)',
    rule: 'FREQ=YEARLY;BYMONTH=1,6',
    locale: 'ru',
    expected: 'В январе и июне',
  },
  {
    name: 'yearly every-2-years two months (en)',
    rule: 'FREQ=YEARLY;INTERVAL=2;BYMONTH=1,6',
    locale: 'en',
    expected: 'Every 2 years in January and June',
  },
  {
    name: 'yearly every-2-years two months (ru)',
    rule: 'FREQ=YEARLY;INTERVAL=2;BYMONTH=1,6',
    locale: 'ru',
    expected: 'Каждые 2 года в январе и июне',
  },

  // ---- HOURLY / MINUTELY / SECONDLY smoke ----
  { name: 'hourly (en)', rule: 'FREQ=HOURLY;INTERVAL=3', locale: 'en', expected: 'Every 3 hours' },
  { name: 'hourly (ru)', rule: 'FREQ=HOURLY;INTERVAL=3', locale: 'ru', expected: 'Каждые 3 часа' },
  {
    name: 'minutely (en)',
    rule: 'FREQ=MINUTELY;INTERVAL=15',
    locale: 'en',
    expected: 'Every 15 minutes',
  },
  {
    name: 'minutely (ru)',
    rule: 'FREQ=MINUTELY;INTERVAL=15',
    locale: 'ru',
    expected: 'Каждые 15 минут',
  },
  {
    name: 'secondly (en)',
    rule: 'FREQ=SECONDLY;INTERVAL=30',
    locale: 'en',
    expected: 'Every 30 seconds',
  },
  {
    name: 'secondly (ru)',
    rule: 'FREQ=SECONDLY;INTERVAL=30',
    locale: 'ru',
    expected: 'Каждые 30 секунд',
  },

  // ---- COUNT and UNTIL, combined with different FREQ ----
  {
    name: 'weekly with count (en)',
    rule: 'FREQ=WEEKLY;COUNT=10',
    locale: 'en',
    expected: 'Every week for 10 times',
  },
  {
    name: 'weekly with count (ru)',
    rule: 'FREQ=WEEKLY;COUNT=10',
    locale: 'ru',
    expected: 'Каждую неделю 10 раз',
  },
  {
    name: 'weekly with count=1 (ru)',
    rule: 'FREQ=WEEKLY;COUNT=1',
    locale: 'ru',
    expected: 'Каждую неделю 1 раз',
  },
  {
    name: 'monthly with count (en)',
    rule: 'FREQ=MONTHLY;COUNT=5',
    locale: 'en',
    expected: 'Every month for 5 times',
  },
  {
    name: 'monthly with count (ru)',
    rule: 'FREQ=MONTHLY;COUNT=5',
    locale: 'ru',
    expected: 'Каждый месяц 5 раз',
  },
  {
    name: 'daily with until (en)',
    rule: 'FREQ=DAILY;UNTIL=20261231T000000Z',
    locale: 'en',
    expected: 'Every day until December 31, 2026',
  },
  {
    name: 'daily with until (ru)',
    rule: 'FREQ=DAILY;UNTIL=20261231T000000Z',
    locale: 'ru',
    expected: 'Каждый день до 31 декабря 2026 г.',
  },

  // ---- BYMONTH + BYDAY combinations ----
  {
    name: 'yearly March 1st Sunday (en)',
    rule: 'FREQ=YEARLY;BYMONTH=3;BYDAY=1SU',
    locale: 'en',
    expected: 'In March on the 1st Sunday',
  },
  {
    name: 'yearly March 1st Sunday, neuter (ru)',
    rule: 'FREQ=YEARLY;BYMONTH=3;BYDAY=1SU',
    locale: 'ru',
    expected: 'В марте в первое воскресенье',
  },
  {
    name: 'yearly two months + plain weekday (en)',
    rule: 'FREQ=YEARLY;BYMONTH=3,4;BYDAY=MO',
    locale: 'en',
    expected: 'In March and April on Monday',
  },
  {
    name: 'yearly two months + plain weekday (ru)',
    rule: 'FREQ=YEARLY;BYMONTH=3,4;BYDAY=MO',
    locale: 'ru',
    expected: 'В марте и апреле по понедельникам',
  },

  // ---- All 12 months, prepositional case (ru) ----
  { name: 'month Jan (ru)', rule: 'FREQ=YEARLY;BYMONTH=1', locale: 'ru', expected: 'В январе' },
  { name: 'month Feb (ru)', rule: 'FREQ=YEARLY;BYMONTH=2', locale: 'ru', expected: 'В феврале' },
  { name: 'month Mar (ru)', rule: 'FREQ=YEARLY;BYMONTH=3', locale: 'ru', expected: 'В марте' },
  { name: 'month Apr (ru)', rule: 'FREQ=YEARLY;BYMONTH=4', locale: 'ru', expected: 'В апреле' },
  { name: 'month May (ru)', rule: 'FREQ=YEARLY;BYMONTH=5', locale: 'ru', expected: 'В мае' },
  { name: 'month Jun (ru)', rule: 'FREQ=YEARLY;BYMONTH=6', locale: 'ru', expected: 'В июне' },
  { name: 'month Jul (ru)', rule: 'FREQ=YEARLY;BYMONTH=7', locale: 'ru', expected: 'В июле' },
  { name: 'month Aug (ru)', rule: 'FREQ=YEARLY;BYMONTH=8', locale: 'ru', expected: 'В августе' },
  { name: 'month Sep (ru)', rule: 'FREQ=YEARLY;BYMONTH=9', locale: 'ru', expected: 'В сентябре' },
  { name: 'month Oct (ru)', rule: 'FREQ=YEARLY;BYMONTH=10', locale: 'ru', expected: 'В октябре' },
  { name: 'month Nov (ru)', rule: 'FREQ=YEARLY;BYMONTH=11', locale: 'ru', expected: 'В ноябре' },
  { name: 'month Dec (ru)', rule: 'FREQ=YEARLY;BYMONTH=12', locale: 'ru', expected: 'В декабре' },

  // ---- All 7 weekdays individually, dative plural (ru); Monday already
  // covered above ("weekly one weekday (ru)") ----
  {
    name: 'weekday Tuesday alone (ru)',
    rule: 'FREQ=WEEKLY;BYDAY=TU',
    locale: 'ru',
    expected: 'Каждую неделю по вторникам',
  },
  {
    name: 'weekday Wednesday alone (ru)',
    rule: 'FREQ=WEEKLY;BYDAY=WE',
    locale: 'ru',
    expected: 'Каждую неделю по средам',
  },
  {
    name: 'weekday Thursday alone (ru)',
    rule: 'FREQ=WEEKLY;BYDAY=TH',
    locale: 'ru',
    expected: 'Каждую неделю по четвергам',
  },
  {
    name: 'weekday Friday alone (ru)',
    rule: 'FREQ=WEEKLY;BYDAY=FR',
    locale: 'ru',
    expected: 'Каждую неделю по пятницам',
  },
  {
    name: 'weekday Saturday alone (ru)',
    rule: 'FREQ=WEEKLY;BYDAY=SA',
    locale: 'ru',
    expected: 'Каждую неделю по субботам',
  },
  {
    name: 'weekday Sunday alone (ru)',
    rule: 'FREQ=WEEKLY;BYDAY=SU',
    locale: 'ru',
    expected: 'Каждую неделю по воскресеньям',
  },

  // ---- Nth-weekday ordinal positions 2-5, one representative per gender
  // (masculine/feminine/neuter) -- position 1 is already covered above for
  // all 7 weekdays. Position 2 (masculine/feminine/neuter) specifically
  // regression-tests the "в" -> "во" preposition shift before "второй/
  // вторую/второе" ("во второй", not "в второй"). ----
  {
    name: 'nth weekday 2nd, masculine -- "во", not "в" (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=TU;BYSETPOS=2',
    locale: 'ru',
    expected: 'Каждый месяц во второй вторник',
  },
  {
    name: 'nth weekday 2nd, feminine -- "во", not "в" (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=FR;BYSETPOS=2',
    locale: 'ru',
    expected: 'Каждый месяц во вторую пятницу',
  },
  {
    name: 'nth weekday 2nd, neuter -- "во", not "в" (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=SU;BYSETPOS=2',
    locale: 'ru',
    expected: 'Каждый месяц во второе воскресенье',
  },
  {
    name: 'nth weekday 3rd, masculine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=MO;BYSETPOS=3',
    locale: 'ru',
    expected: 'Каждый месяц в третий понедельник',
  },
  {
    name: 'nth weekday 3rd, feminine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=WE;BYSETPOS=3',
    locale: 'ru',
    expected: 'Каждый месяц в третью среду',
  },
  {
    name: 'nth weekday 3rd, neuter (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=SU;BYSETPOS=3',
    locale: 'ru',
    expected: 'Каждый месяц в третье воскресенье',
  },
  {
    name: 'nth weekday 4th, masculine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=TH;BYSETPOS=4',
    locale: 'ru',
    expected: 'Каждый месяц в четвёртый четверг',
  },
  {
    name: 'nth weekday 4th, feminine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=SA;BYSETPOS=4',
    locale: 'ru',
    expected: 'Каждый месяц в четвёртую субботу',
  },
  {
    name: 'nth weekday 4th, neuter (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=SU;BYSETPOS=4',
    locale: 'ru',
    expected: 'Каждый месяц в четвёртое воскресенье',
  },
  {
    name: 'nth weekday 5th, masculine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=MO;BYSETPOS=5',
    locale: 'ru',
    expected: 'Каждый месяц в пятый понедельник',
  },
  {
    name: 'nth weekday 5th, feminine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=FR;BYSETPOS=5',
    locale: 'ru',
    expected: 'Каждый месяц в пятую пятницу',
  },
  {
    name: 'nth weekday 5th, neuter (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=SU;BYSETPOS=5',
    locale: 'ru',
    expected: 'Каждый месяц в пятое воскресенье',
  },

  // ---- Negative nth-weekday positions across genders. -1 feminine and -2
  // masculine/feminine are already covered above/in rrule-to-text.test.ts. ----
  {
    name: 'nth weekday last, masculine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=-1MO',
    locale: 'ru',
    expected: 'Каждый месяц в последний понедельник',
  },
  {
    name: 'nth weekday last, neuter (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=-1SU',
    locale: 'ru',
    expected: 'Каждый месяц в последнее воскресенье',
  },
  {
    name: 'nth weekday 3rd-to-last, masculine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=TU;BYSETPOS=-3',
    locale: 'ru',
    expected: 'Каждый месяц в 3-й с конца вторник',
  },
  {
    name: 'nth weekday 3rd-to-last, feminine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=WE;BYSETPOS=-3',
    locale: 'ru',
    expected: 'Каждый месяц в 3-я с конца среду',
  },
  {
    name: 'nth weekday 3rd-to-last, neuter (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=SU;BYSETPOS=-3',
    locale: 'ru',
    expected: 'Каждый месяц в 3-е с конца воскресенье',
  },
  {
    name: 'nth weekday 4th-to-last, masculine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=TH;BYSETPOS=-4',
    locale: 'ru',
    expected: 'Каждый месяц в 4-й с конца четверг',
  },
  {
    name: 'nth weekday 4th-to-last, feminine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=SA;BYSETPOS=-4',
    locale: 'ru',
    expected: 'Каждый месяц в 4-я с конца субботу',
  },
  {
    name: 'nth weekday 5th-to-last, masculine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=MO;BYSETPOS=-5',
    locale: 'ru',
    expected: 'Каждый месяц в 5-й с конца понедельник',
  },

  // ---- Numeral agreement (one/few/many) for every FREQ unit other than
  // "day", which is already exhaustively covered above. 2 -> few, 5 -> many,
  // 11 -> many (the "teens" exception), 21 -> one. ----
  {
    name: 'year interval 2, few -> "года" (ru)',
    rule: 'FREQ=YEARLY;INTERVAL=2',
    locale: 'ru',
    expected: 'Каждые 2 года',
  },
  {
    name: 'year interval 5, many -> "лет" (ru)',
    rule: 'FREQ=YEARLY;INTERVAL=5',
    locale: 'ru',
    expected: 'Каждые 5 лет',
  },
  {
    name: 'year interval 11, many (teens exception) -> "лет" (ru)',
    rule: 'FREQ=YEARLY;INTERVAL=11',
    locale: 'ru',
    expected: 'Каждые 11 лет',
  },
  {
    name: 'year interval 21, one -> "год" (ru)',
    rule: 'FREQ=YEARLY;INTERVAL=21',
    locale: 'ru',
    expected: 'Каждые 21 год',
  },
  {
    name: 'month interval 2, few -> "месяца" (ru)',
    rule: 'FREQ=MONTHLY;INTERVAL=2',
    locale: 'ru',
    expected: 'Каждые 2 месяца',
  },
  {
    name: 'month interval 5, many -> "месяцев" (ru)',
    rule: 'FREQ=MONTHLY;INTERVAL=5',
    locale: 'ru',
    expected: 'Каждые 5 месяцев',
  },
  {
    name: 'month interval 11, many (teens exception) -> "месяцев" (ru)',
    rule: 'FREQ=MONTHLY;INTERVAL=11',
    locale: 'ru',
    expected: 'Каждые 11 месяцев',
  },
  {
    name: 'month interval 21, one -> "месяц" (ru)',
    rule: 'FREQ=MONTHLY;INTERVAL=21',
    locale: 'ru',
    expected: 'Каждые 21 месяц',
  },
  {
    name: 'week interval 2, few -> "недели" (ru)',
    rule: 'FREQ=WEEKLY;INTERVAL=2',
    locale: 'ru',
    expected: 'Каждые 2 недели',
  },
  {
    name: 'week interval 5, many -> "недель" (ru)',
    rule: 'FREQ=WEEKLY;INTERVAL=5',
    locale: 'ru',
    expected: 'Каждые 5 недель',
  },
  {
    name: 'week interval 11, many (teens exception) -> "недель" (ru)',
    rule: 'FREQ=WEEKLY;INTERVAL=11',
    locale: 'ru',
    expected: 'Каждые 11 недель',
  },
  {
    name: 'week interval 21, one -> "неделя" (ru)',
    rule: 'FREQ=WEEKLY;INTERVAL=21',
    locale: 'ru',
    expected: 'Каждые 21 неделя',
  },
  {
    name: 'hour interval 2, few -> "часа" (ru)',
    rule: 'FREQ=HOURLY;INTERVAL=2',
    locale: 'ru',
    expected: 'Каждые 2 часа',
  },
  {
    name: 'hour interval 5, many -> "часов" (ru)',
    rule: 'FREQ=HOURLY;INTERVAL=5',
    locale: 'ru',
    expected: 'Каждые 5 часов',
  },
  {
    name: 'hour interval 11, many (teens exception) -> "часов" (ru)',
    rule: 'FREQ=HOURLY;INTERVAL=11',
    locale: 'ru',
    expected: 'Каждые 11 часов',
  },
  {
    name: 'hour interval 21, one -> "час" (ru)',
    rule: 'FREQ=HOURLY;INTERVAL=21',
    locale: 'ru',
    expected: 'Каждые 21 час',
  },
  {
    name: 'minute interval 2, few -> "минуты" (ru)',
    rule: 'FREQ=MINUTELY;INTERVAL=2',
    locale: 'ru',
    expected: 'Каждые 2 минуты',
  },
  {
    name: 'minute interval 5, many -> "минут" (ru)',
    rule: 'FREQ=MINUTELY;INTERVAL=5',
    locale: 'ru',
    expected: 'Каждые 5 минут',
  },
  {
    name: 'minute interval 11, many (teens exception) -> "минут" (ru)',
    rule: 'FREQ=MINUTELY;INTERVAL=11',
    locale: 'ru',
    expected: 'Каждые 11 минут',
  },
  {
    name: 'minute interval 21, one -> "минута" (ru)',
    rule: 'FREQ=MINUTELY;INTERVAL=21',
    locale: 'ru',
    expected: 'Каждые 21 минута',
  },
  {
    name: 'second interval 2, few -> "секунды" (ru)',
    rule: 'FREQ=SECONDLY;INTERVAL=2',
    locale: 'ru',
    expected: 'Каждые 2 секунды',
  },
  {
    name: 'second interval 5, many -> "секунд" (ru)',
    rule: 'FREQ=SECONDLY;INTERVAL=5',
    locale: 'ru',
    expected: 'Каждые 5 секунд',
  },
  {
    name: 'second interval 11, many (teens exception) -> "секунд" (ru)',
    rule: 'FREQ=SECONDLY;INTERVAL=11',
    locale: 'ru',
    expected: 'Каждые 11 секунд',
  },
  {
    name: 'second interval 21, one -> "секунда" (ru)',
    rule: 'FREQ=SECONDLY;INTERVAL=21',
    locale: 'ru',
    expected: 'Каждые 21 секунда',
  },

  // ---- BYMONTHDAY: mixed positive+negative, and 3+ fragments (regression-
  // tests the natural "a, b и c" / "a, b and c" join added for 3+ fragments,
  // instead of a monotonous repeated "и"/"and") ----
  {
    name: 'monthday mixed positive + last day (en)',
    rule: 'FREQ=MONTHLY;BYMONTHDAY=1,-1',
    locale: 'en',
    expected: 'Every month on the 1st and on the last day of the month',
  },
  {
    name: 'monthday mixed positive + last day (ru)',
    rule: 'FREQ=MONTHLY;BYMONTHDAY=1,-1',
    locale: 'ru',
    expected: 'Каждый месяц 1-го числа и в последний день месяца',
  },
  {
    name: 'monthday 3rd-to-last, standalone (ru)',
    rule: 'FREQ=MONTHLY;BYMONTHDAY=-3',
    locale: 'ru',
    expected: 'Каждый месяц 3-й день с конца месяца',
  },
  {
    name: 'monthday 3 fragments, natural "a, b и c" join (ru)',
    rule: 'FREQ=MONTHLY;BYMONTHDAY=15,-1,-2',
    locale: 'ru',
    expected: 'Каждый месяц 15-го числа, в последний день месяца и 2-й день с конца месяца',
  },
  {
    name: 'monthday 3 negative fragments, natural "a, b и c" join (ru)',
    rule: 'FREQ=MONTHLY;BYMONTHDAY=-1,-2,-3',
    locale: 'ru',
    expected:
      'Каждый месяц в последний день месяца, 2-й день с конца месяца и 3-й день с конца месяца',
  },
  {
    name: 'monthday 3 fragments, natural "a, b and c" join (en)',
    rule: 'FREQ=MONTHLY;BYMONTHDAY=15,-1,-2',
    locale: 'en',
    expected:
      'Every month on the 15th, on the last day of the month and on the 2nd-to-last day of the month',
  },

  // ---- WEEKLY + full business week collapses to the "weekdays" idiom the
  // same way DAILY does. This idiom collapse lives in weekdaysPhrase() and
  // applies regardless of INTERVAL; only the *frequency phrase* itself
  // ("Every week" / "Каждую неделю") is additionally omitted when
  // interval === 1, since with interval !== 1 it's still needed to convey
  // the "every Nth week" part. ----
  {
    name: 'weekly full business week collapses to "on weekdays" (en)',
    rule: 'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR',
    locale: 'en',
    expected: 'On weekdays',
  },
  {
    name: 'weekly full business week collapses to "По будням" (ru)',
    rule: 'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR',
    locale: 'ru',
    expected: 'По будням',
  },
  {
    name: 'weekly interval=2 + business week still uses the "weekdays" idiom, frequency phrase kept (en)',
    rule: 'FREQ=WEEKLY;INTERVAL=2;BYDAY=MO,TU,WE,TH,FR',
    locale: 'en',
    expected: 'Every 2 weeks on weekdays',
  },
  {
    name: 'weekly interval=2 + business week still uses the "по будням" idiom, frequency phrase kept (ru)',
    rule: 'FREQ=WEEKLY;INTERVAL=2;BYDAY=MO,TU,WE,TH,FR',
    locale: 'ru',
    expected: 'Каждые 2 недели по будням',
  },

  // ---- BYYEARDAY / BYWEEKNO exact approximate-match wording (ru) ----
  {
    name: 'BYYEARDAY exact approximate-match wording (ru)',
    rule: 'FREQ=YEARLY;BYYEARDAY=1,100',
    locale: 'ru',
    expected: 'Каждый год (~ приблизительно)',
  },
  {
    name: 'BYWEEKNO exact approximate-match wording (ru)',
    rule: 'FREQ=MONTHLY;BYWEEKNO=1',
    locale: 'ru',
    expected: 'Каждый месяц (~ приблизительно)',
  },

  // ---- 3+ nth-weekday fragments (multiple BYSETPOS x multiple BYDAY):
  // regression-tests the natural "a, b и c" / "a, b and c" join added to
  // buildWeekdayClause() in the core engine, instead of a monotonous
  // repeated "и"/"and" between every fragment. ----
  {
    name: 'nth weekday 3x3 cross product, natural "a, b and c" join (en)',
    rule: 'FREQ=MONTHLY;BYDAY=MO,WE,FR;BYSETPOS=1,2,-1',
    locale: 'en',
    expected:
      'Every month on the 1st Monday, on the 1st Wednesday, on the 1st Friday, on the 2nd Monday, on the 2nd Wednesday, on the 2nd Friday, on the last Monday, on the last Wednesday and on the last Friday',
  },
  {
    name: 'nth weekday 3x3 cross product, natural "a, b и c" join (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=MO,WE,FR;BYSETPOS=1,2,-1',
    locale: 'ru',
    expected:
      'Каждый месяц в первый понедельник, в первую среду, в первую пятницу, во второй понедельник, во вторую среду, во вторую пятницу, в последний понедельник, в последнюю среду и в последнюю пятницу',
  },
];
