export interface Fixture {
  /** A short, human-readable test name. */
  name: string;
  rule: string;
  locale: 'en' | 'ru';
  expected: string;
}

/**
 * Golden fixtures covering every FREQ value, INTERVAL, COUNT, UNTIL, BYDAY
 * (including numeric-prefixed shorthand and BYSETPOS), BYMONTHDAY (including
 * negative), BYMONTH, and combinations thereof, for both bundled locales.
 *
 * These strings were generated by this library itself and hand-reviewed for
 * grammatical correctness (particularly the Russian case/gender agreement).
 * `tests/regression.test.ts` cross-checks the `en` subset against `rrule`'s
 * own `toText()` and documents every intentional divergence.
 */
export const fixtures: Fixture[] = [
  // ---- Baseline frequencies, no modifiers ----
  { name: 'yearly plain (en)', rule: 'FREQ=YEARLY', locale: 'en', expected: 'Every year' },
  { name: 'yearly plain (ru)', rule: 'FREQ=YEARLY', locale: 'ru', expected: 'Каждый год' },
  { name: 'monthly plain (en)', rule: 'FREQ=MONTHLY', locale: 'en', expected: 'Every month' },
  { name: 'monthly plain (ru)', rule: 'FREQ=MONTHLY', locale: 'ru', expected: 'Каждый месяц' },
  { name: 'weekly plain (en)', rule: 'FREQ=WEEKLY', locale: 'en', expected: 'Every week' },
  { name: 'weekly plain (ru)', rule: 'FREQ=WEEKLY', locale: 'ru', expected: 'Каждую неделю' },

  // ---- DAILY + INTERVAL, incl. Russian numeral edge cases (1, 2, 5, 11, 21, 25) ----
  {
    name: 'daily interval 1 (en)',
    rule: 'FREQ=DAILY;INTERVAL=1',
    locale: 'en',
    expected: 'Every day',
  },
  {
    name: 'daily interval 1 (ru)',
    rule: 'FREQ=DAILY;INTERVAL=1',
    locale: 'ru',
    expected: 'Каждый день',
  },
  {
    name: 'daily interval 2 (en)',
    rule: 'FREQ=DAILY;INTERVAL=2',
    locale: 'en',
    expected: 'Every 2 days',
  },
  {
    name: 'daily interval 2 (ru)',
    rule: 'FREQ=DAILY;INTERVAL=2',
    locale: 'ru',
    expected: 'Каждые 2 дня',
  },
  {
    name: 'daily interval 5 (ru)',
    rule: 'FREQ=DAILY;INTERVAL=5',
    locale: 'ru',
    expected: 'Каждые 5 дней',
  },
  {
    name: 'daily interval 11 (ru)',
    rule: 'FREQ=DAILY;INTERVAL=11',
    locale: 'ru',
    expected: 'Каждые 11 дней',
  },
  {
    name: 'daily interval 21 (ru)',
    rule: 'FREQ=DAILY;INTERVAL=21',
    locale: 'ru',
    expected: 'Каждые 21 день',
  },
  {
    name: 'daily interval 25 (ru)',
    rule: 'FREQ=DAILY;INTERVAL=25',
    locale: 'ru',
    expected: 'Каждые 25 дней',
  },

  // ---- WEEKLY + BYDAY: one day, several days, and the "every weekday" / "weekend" special cases ----
  {
    name: 'weekly one weekday (en)',
    rule: 'FREQ=WEEKLY;BYDAY=MO',
    locale: 'en',
    expected: 'Every week on Monday',
  },
  {
    name: 'weekly one weekday (ru)',
    rule: 'FREQ=WEEKLY;BYDAY=MO',
    locale: 'ru',
    expected: 'Каждую неделю по понедельникам',
  },
  {
    name: 'weekly several weekdays (en)',
    rule: 'FREQ=WEEKLY;BYDAY=MO,WE,FR',
    locale: 'en',
    expected: 'Every week on Monday, Wednesday and Friday',
  },
  {
    name: 'weekly several weekdays (ru)',
    rule: 'FREQ=WEEKLY;BYDAY=MO,WE,FR',
    locale: 'ru',
    expected: 'Каждую неделю по понедельникам, средам и пятницам',
  },
  {
    name: 'daily + full business week collapses to "on weekdays" (en)',
    rule: 'FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR',
    locale: 'en',
    expected: 'On weekdays',
  },
  {
    name: 'daily + full business week collapses to "по будням" (ru)',
    rule: 'FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR',
    locale: 'ru',
    expected: 'По будням',
  },
  {
    name: 'weekly + Sat/Sun collapses to "on weekends" (en)',
    rule: 'FREQ=WEEKLY;BYDAY=SA,SU',
    locale: 'en',
    expected: 'Every week on weekends',
  },
  {
    name: 'weekly + Sat/Sun collapses to "по выходным" (ru)',
    rule: 'FREQ=WEEKLY;BYDAY=SA,SU',
    locale: 'ru',
    expected: 'Каждую неделю по выходным',
  },

  // ---- MONTHLY + BYMONTHDAY: positive, negative, and "last day" ----
  {
    name: 'monthly last day (en)',
    rule: 'FREQ=MONTHLY;BYMONTHDAY=-1',
    locale: 'en',
    expected: 'Every month on the last day of the month',
  },
  {
    name: 'monthly last day (ru)',
    rule: 'FREQ=MONTHLY;BYMONTHDAY=-1',
    locale: 'ru',
    expected: 'Каждый месяц в последний день месяца',
  },
  {
    name: 'monthly two positive month-days (en)',
    rule: 'FREQ=MONTHLY;BYMONTHDAY=1,15',
    locale: 'en',
    expected: 'Every month on the 1st and 15th',
  },
  {
    name: 'monthly two positive month-days (ru)',
    rule: 'FREQ=MONTHLY;BYMONTHDAY=1,15',
    locale: 'ru',
    expected: 'Каждый месяц 1-го и 15-го числа',
  },
  {
    name: 'monthly 2nd-to-last day (en)',
    rule: 'FREQ=MONTHLY;BYMONTHDAY=-2',
    locale: 'en',
    expected: 'Every month on the 2nd-to-last day of the month',
  },
  {
    name: 'monthly 2nd-to-last day (ru)',
    rule: 'FREQ=MONTHLY;BYMONTHDAY=-2',
    locale: 'ru',
    expected: 'Каждый месяц 2-й день с конца месяца',
  },

  // ---- MONTHLY + BYDAY + BYSETPOS ("the Nth weekday") -- every weekday gender, RU ----
  {
    name: 'monthly 1st Monday (en)',
    rule: 'FREQ=MONTHLY;BYDAY=MO;BYSETPOS=1',
    locale: 'en',
    expected: 'Every month on the 1st Monday',
  },
  {
    name: 'monthly 1st Monday, masculine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=MO;BYSETPOS=1',
    locale: 'ru',
    expected: 'Каждый месяц в первый понедельник',
  },
  {
    name: 'monthly 1st Tuesday, masculine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=TU;BYSETPOS=1',
    locale: 'ru',
    expected: 'Каждый месяц в первый вторник',
  },
  {
    name: 'monthly 1st Wednesday, feminine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=WE;BYSETPOS=1',
    locale: 'ru',
    expected: 'Каждый месяц в первую среду',
  },
  {
    name: 'monthly 1st Thursday, masculine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=TH;BYSETPOS=1',
    locale: 'ru',
    expected: 'Каждый месяц в первый четверг',
  },
  {
    name: 'monthly 1st Friday, feminine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=FR;BYSETPOS=1',
    locale: 'ru',
    expected: 'Каждый месяц в первую пятницу',
  },
  {
    name: 'monthly 1st Saturday, feminine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=SA;BYSETPOS=1',
    locale: 'ru',
    expected: 'Каждый месяц в первую субботу',
  },
  {
    name: 'monthly 1st Sunday, neuter (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=SU;BYSETPOS=1',
    locale: 'ru',
    expected: 'Каждый месяц в первое воскресенье',
  },
  {
    name: 'monthly last Friday, shorthand -1FR (en)',
    rule: 'FREQ=MONTHLY;BYDAY=-1FR',
    locale: 'en',
    expected: 'Every month on the last Friday',
  },
  {
    name: 'monthly last Friday, shorthand -1FR, feminine (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=-1FR',
    locale: 'ru',
    expected: 'Каждый месяц в последнюю пятницу',
  },
  {
    name: 'monthly mixed shorthand 1MO,-1FR (en)',
    rule: 'FREQ=MONTHLY;BYDAY=1MO,-1FR',
    locale: 'en',
    expected: 'Every month on the 1st Monday and on the last Friday',
  },
  {
    name: 'monthly mixed shorthand 1MO,-1FR (ru)',
    rule: 'FREQ=MONTHLY;BYDAY=1MO,-1FR',
    locale: 'ru',
    expected: 'Каждый месяц в первый понедельник и в последнюю пятницу',
  },

  // ---- YEARLY + BYMONTH ----
  {
    name: 'yearly two months (en)',
    rule: 'FREQ=YEARLY;BYMONTH=1,6',
    locale: 'en',
    expected: 'In January and June',
  },
  {
    name: 'yearly two months (ru)',
    rule: 'FREQ=YEARLY;BYMONTH=1,6',
    locale: 'ru',
    expected: 'В январе и июне',
  },
  {
    name: 'yearly every-2-years two months (en)',
    rule: 'FREQ=YEARLY;INTERVAL=2;BYMONTH=1,6',
    locale: 'en',
    expected: 'Every 2 years in January and June',
  },
  {
    name: 'yearly every-2-years two months (ru)',
    rule: 'FREQ=YEARLY;INTERVAL=2;BYMONTH=1,6',
    locale: 'ru',
    expected: 'Каждые 2 года в январе и июне',
  },

  // ---- HOURLY / MINUTELY / SECONDLY smoke ----
  { name: 'hourly (en)', rule: 'FREQ=HOURLY;INTERVAL=3', locale: 'en', expected: 'Every 3 hours' },
  { name: 'hourly (ru)', rule: 'FREQ=HOURLY;INTERVAL=3', locale: 'ru', expected: 'Каждые 3 часа' },
  {
    name: 'minutely (en)',
    rule: 'FREQ=MINUTELY;INTERVAL=15',
    locale: 'en',
    expected: 'Every 15 minutes',
  },
  {
    name: 'minutely (ru)',
    rule: 'FREQ=MINUTELY;INTERVAL=15',
    locale: 'ru',
    expected: 'Каждые 15 минут',
  },
  {
    name: 'secondly (en)',
    rule: 'FREQ=SECONDLY;INTERVAL=30',
    locale: 'en',
    expected: 'Every 30 seconds',
  },
  {
    name: 'secondly (ru)',
    rule: 'FREQ=SECONDLY;INTERVAL=30',
    locale: 'ru',
    expected: 'Каждые 30 секунд',
  },

  // ---- COUNT and UNTIL, combined with different FREQ ----
  {
    name: 'weekly with count (en)',
    rule: 'FREQ=WEEKLY;COUNT=10',
    locale: 'en',
    expected: 'Every week for 10 times',
  },
  {
    name: 'weekly with count (ru)',
    rule: 'FREQ=WEEKLY;COUNT=10',
    locale: 'ru',
    expected: 'Каждую неделю 10 раз',
  },
  {
    name: 'weekly with count=1 (ru)',
    rule: 'FREQ=WEEKLY;COUNT=1',
    locale: 'ru',
    expected: 'Каждую неделю 1 раз',
  },
  {
    name: 'monthly with count (en)',
    rule: 'FREQ=MONTHLY;COUNT=5',
    locale: 'en',
    expected: 'Every month for 5 times',
  },
  {
    name: 'monthly with count (ru)',
    rule: 'FREQ=MONTHLY;COUNT=5',
    locale: 'ru',
    expected: 'Каждый месяц 5 раз',
  },
  {
    name: 'daily with until (en)',
    rule: 'FREQ=DAILY;UNTIL=20261231T000000Z',
    locale: 'en',
    expected: 'Every day until December 31, 2026',
  },
  {
    name: 'daily with until (ru)',
    rule: 'FREQ=DAILY;UNTIL=20261231T000000Z',
    locale: 'ru',
    expected: 'Каждый день до 31 декабря 2026 г.',
  },

  // ---- BYMONTH + BYDAY combinations ----
  {
    name: 'yearly March 1st Sunday (en)',
    rule: 'FREQ=YEARLY;BYMONTH=3;BYDAY=1SU',
    locale: 'en',
    expected: 'In March on the 1st Sunday',
  },
  {
    name: 'yearly March 1st Sunday, neuter (ru)',
    rule: 'FREQ=YEARLY;BYMONTH=3;BYDAY=1SU',
    locale: 'ru',
    expected: 'В марте в первое воскресенье',
  },
  {
    name: 'yearly two months + plain weekday (en)',
    rule: 'FREQ=YEARLY;BYMONTH=3,4;BYDAY=MO',
    locale: 'en',
    expected: 'In March and April on Monday',
  },
  {
    name: 'yearly two months + plain weekday (ru)',
    rule: 'FREQ=YEARLY;BYMONTH=3,4;BYDAY=MO',
    locale: 'ru',
    expected: 'В марте и апреле по понедельникам',
  },
];
